# Generated by Django 4.2 on 2026-08-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('distance_km', models.DecimalField(decimal_places=3, help_text='Trail length in kilometers', max_digits=6)),
                ('elevation_gain', models.IntegerField(help_text='Elevation gain in meters')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Expert', 'Expert')], default='Moderate', max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['distance_km'],
            },
        ),
    ]
