# Generated by Django 4.2 on 2026-08-17 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(help_text='e.g. Cascade Range, Olympic Peninsula', max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance_km',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AddField(
            model_name='trail',
            name='park',
            field=models.ForeignKey(blank=True, help_text='Park or wilderness area this trail belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trails', to='trails.park'),
        ),
    ]
